### ISSUE TITLE
Could not find Adafruit_NeoPixel.h

### ISSUE THREAD

**Issue by yorecode** [sillycowvalley/Hopper#11]
To get a clean upload of first run Hopper, on an RPi RP2040 Pico W, had to work around ifdef RP2040.  
Line 8 of Platform.cpp (and 6 other occurrences) of `#ifdef RP2040` to avoid loading Adafruit NeoPixel code.

After those changes, succeeded in uploading a nice copy of Hopper on to the Pico W, and blinkin' the light.

And some kudos to you, Michael, @biggertigger, for Hopper.  It feels like this is going to be a fun explore, and time well spent learning.

**Comment by sillycowvalley** [comment]
Excellent. Nicely done.
I should add instructions for the growing list of libraries that we're depending on in the Arduino IDE. My objective is to have a minimal set of UF2 files under releases so most people don't need to bother with the Arduino IDE. I'd be curious to know if dragging and dropping the latest Pico W UF2 file works for you too:
https://github.com/sillycowvalley/Hopper/releases

FYI: the NeoPixel library that ended up working for me was the original "Adafruit NeoPixel" one (currently on version 1.12.0) installed via the Arduino IDE library manager but found here:
https://github.com/adafruit/Adafruit_NeoPixel

**Comment by yorecode** [comment]
Just flashed the HopperPicoW.uf2 from the releases link, and yep.  Light is blinkin'.   Using *Source/Samples/MCU/Blink.hs*, without the sidetrip into Arduino.

Tried ws114.hs on another Pico W after flashing the release UF2, no Arduino pass, and the blue, green, red screen tests are running fine.   The WS 1.14inch LCD is plugged into a WaveShare Dual Expander sistered with the 10DOF IMU  (from the Pi-Pico(W)-Kit-B, the Wifi version of the webpage is 404), https://www.waveshare.com/wiki/Raspberry-Pi-Pico-Kit-B

Working the beauty.

Initial trials with the WebServer.hs have been less successful getting connected (MCU/Secrets2 had to be renamed to Secrets with the local credentials put in Connect.hs).  Will keep trying, as this could very well be a local setup problem.

**Comment by sillycowvalley** [comment]
Thanks Brian. I really appreciate the testing and the feedback.
I need to spend some more time on the Pico W web/wifi initialization. I could not find an obvious "reset" API like the Challenger library has ... so ... lots of power cycling and new sessions (rather than incremental debugging the same session). Tedious. But probably just something I'm missing.

**Comment by sillycowvalley** [comment]
Added build instructions that include the list of required libraries by name for the Arduino portable runtime project:
https://github.com/sillycowvalley/Hopper/tree/main/Runtimes/Arduino/HopperPortable#readme
