### ISSUE TITLE
Discussions

### ISSUE THREAD

**Issue by yorecode** [sillycowvalley/Hopper#12]
Hello, Michael

I'd like to chat, somewhere.  For now, this.

How do you run the hexe's on Windows for testing?  Am I missing something obvious?

And thanks.  :-)

**Comment by sillycowvalley** [comment]
Hi Brian,

Here's an invite to the Hopper Discord server (very quiet right now but a better platform for chat / discussion):
https://discord.gg/KK3wpfCh

hexe's run under the Hopper runtime. The current Hopper runtime on Windows is the HopperNET.exe in the distribution / release.

hexe's that are built for Windows will run in that runtime (like the shell, the editor, the compiler, etc).
Some features are platform specific though (like GPIO pins, SPI, I2C, etc) so those hexe's will only run properly on their target runtime, MCU's in this case.

And just in case you haven't discovered the youtube videos yet:
https://www.youtube.com/@biggertigger/playlists
